### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "coletoo122@gmail.com",
    "password": "afafasf21fsa"
} 

### Delete an existing user
DELETE http://localhost:3000/auth/3