### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "coletoo122@gmail.com",
    "password": "afafasf21fsa"
} 

### Get a user by id
GET  http://localhost:3000/auth/8

### Delete an existing user
DELETE http://localhost:3000/auth/6

### Find all users with a given email
GET http://localhost:3000/auth/?email=coletoo122@gmail.com

